const Types = {
    SET_AUTH_TRUE: "SETAUTHTRUE",
    SET_AUTH_FALSE: "SETAUTHFALSE",
    SET_TOKEN: "SETTOKEN",
    SET_LOGIN: "SET_LOGIN",
    SET_PASSWORD: 'SET_PASSWORD',
    SET_USER: 'SET_USER',
    RESET_USER: 'RESET_USER'
}
export default Types;